authorization/api/urls.py
from django.conf import settings
from django.urls import include, path
from rest_framework.routers import DefaultRouter, SimpleRouter

from .views import RequestSMSCodeView, UserViewSet, VerifySMSCodeView

app_name = 'api_v1'

Router = DefaultRouter if settings.DEBUG else SimpleRouter

router_v1 = Router()
router_v1.register(r'users', UserViewSet, basename='users')
router_v1.register(r'request-sms', RequestSMSCodeView, basename='request_sms')
router_v1.register(r'verify-sms', VerifySMSCodeView, basename='verify_sms')


urlpatterns = [
    path('', include(router_v1.urls), name='routers'),
    path('auth/', include('djoser.urls.authtoken'), name='auth'),
]

authorization/authorization/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('api/', include('api.urls'))
]

schema_view = get_schema_view(
    openapi.Info(
        title="Authorization API",
        default_version='v1',
        description="Документация для тестового задания.",
        contact=openapi.Contact(email="Xcision@ya.ru"),
    ), public=True, permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
            name='schema-redoc'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authorization/pages/urls.py
from django.urls import path

from .views import (AuthorizationFormView, ConfirmFormView, LogoutView,
                    SuccessView)

app_name = 'pages'

urlpatterns = [
    path('', AuthorizationFormView.as_view(), name='auth_form'),
    path('confirm/', ConfirmFormView.as_view(), name='confirm_form'),
    path('success/', SuccessView.as_view(), name='success'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

authorization/templates/pages/authorization_from.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card" style="width: 100%; max-width: 400px;">
            <div class="card-body">
                <h2 class="text-center">Авторизация</h2>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %} 
                    <button type="submit" class="btn btn-primary btn-block">Войти</button> 
                </form>
            </div>
        </div>
    </div>
</body>
</html>

authorization/templates/pages/confirm_form.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проверочный код</title>
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card" style="width: 100%; max-width: 400px;">
            <div class="card-body">
                <h2 class="text-center">Введите проверочный код</h2>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %} 
                    {{ form.phone_number }}
                    <button type="submit" class="btn btn-primary btn-block">Подтвердить</button> 
                    
                </form>
            </div>
        </div>
    </div>
    <div class="position-fixed bottom-0 start-50 translate-middle-x mb-3 text-center">
        {{ sms }}
    </div>
</body>
</html>

authorization/templates/pages/success.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Успешный вход</title>
</head>
<body>
    <div class="container">
        <h1>Добро пожаловать, {% if user.username %}{{user.username}}{% else %}{{user.phone_number}}{% endif %}!</h1>
        <h3>Вы успешно вошли в свою учетную запись.
        <p>Ваша реферальная ссылка {{ user.referal_code }}.</p></h3>
        <div class="justify-content-center col-6">
                <h2>Редактировать Информация о пользователе:</h2>
                <form method='post' enctype="multipart/form-data" id='form1'>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="btn-group-vertical w-100"> 
                        {% bootstrap_button button_type="submit" content="Отправить" %}
                </form>
            </div>
            <h5>Вы приглосили</h5>
            {% if invited %}
            {% for invite in invited %}
                <li>{{ invite.phone_number }}</li>
            {% endfor %}{% endif %}
        </div>


        <a href="{% url 'pages:logout' %}">Выйти</a>
    </div>
</body>
</html>